// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmqfonczkedrrdnfwpfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtcWZvbmN6a2VkcnJkbmZ3cGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzg3NTUsImV4cCI6MjA3MzYxNDc1NX0.5IagPSXfCArWiS-ySfwbZ6Bp_FH3RQSKjSEpkWslokA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});